### ISSUE TITLE
Unable to find a specification for `AZExpandable (~> 0.0)`

### ISSUE THREAD

**Issue by brandoncordell** [azonov/ExpandableTable#2]
I'm unable to install this pod in my project. This is a greenfield project with nothing really in it yet. Here's my Podfile.

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'AppName' do
  pod 'AZExpandable', '~> 0.0'
end
```

Am I doing something wrong? Feel free to close this if it's an issue with Cocoapods.

**Comment by azonov** [comment]
Hello, I rechecked, works fine
First of all, remove '~> 0.0', valid version 0.0.1, and versioning is not required,
Then, if still fails, use pod update.

I'm ready to help with other details

**Comment by brandoncordell** [comment]
Thanks @azonov! `pod install` kept failing until I ran `pod update`.
