### ISSUE TITLE
How can I unexpand the expandedCell from a button out of tableView? 

### ISSUE THREAD

**Issue by GokmenAkar** [azonov/ExpandableTable#3]
I can't close the expanded cell, It pretends like there is a one more cell and it causes an error in cellForRowAt when the tableView reloaded with new data. 

Thank you!

**Comment by azonov** [comment]
Oh, man, sounds terrible, could you make gist example or provide case here, I will test it

**Comment by GokmenAkar** [comment]
@azonov We will release the app on store today, I need urgent help. 

This is the error when I try to call the the toggleItem function from outside of didselect method, with same indexpath. 

this what i did before  i call the func in **tableView** **didSelect** method, 
```
self.indexPathTrack = indexPath
            toggleItem(at: indexPath)
```

after that, i try to call unexpand the cell when I reload tableView with new data. 

This is in **didSelect** method of **collectionView** , cause data chages when didSelect is called. 
`self.toggleItem(at: indexPath)`

and it crashes me, i couldn't figure out. 

`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (13) must be equal to the number of rows contained in that section before the update (21), plus or minus the number of rows inserted or deleted from that section (0 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).' `

**Comment by azonov** [comment]
I didn't test on CollectionView's, still it seem like an issue with toggling, try to call unexpand and reload in dispatch_async, it will be scheduled in the next runloop and calculation must be fixed

**Comment by GokmenAkar** [comment]
@azonov  Not about collectionView, when i try to unexpand with button the tracked cell, it throws same error. but i'll try with async.
