### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by gerchicov-bp** [azonov/ExpandableTable#5]
```
Requirements

iOS 8.0+
Xcode 9.2+
Swift 4.0+

```

I use Swift 4 in my project and install your library via cocoapods. I get some errors with swift version like the following:
`'automaticDimension' has been renamed to 'UITableViewAutomaticDimension'`

**Comment by azonov** [comment]
Hello, 
Thank you for you interest, please run pod update and verify latest version is '1.1.0'. Issue fixed

**Comment by gerchicov-bp** [comment]
thanks, now It seems to be workable
